// Feed posts. type: "text" | "project-update" | "poll"

export const posts = [
  {
    id: "p1",
    author: "amarapatel",
    type: "text",
    createdAt: "2026-07-23T14:20:00Z",
    content:
      "Spent the day migrating our ledger service off a single Postgres instance onto sharded writes. The hardest part wasn't the sharding logic — it was convincing myself the reconciliation job was actually idempotent. Wrote 40 tests just for that one function.",
    tags: ["postgresql", "distributed-systems"],
    likes: 214,
    comments: 18,
    reposts: 12,
  },
  {
    id: "p2",
    author: "kenji_oda",
    type: "project-update",
    createdAt: "2026-07-23T10:05:00Z",
    content:
      "motion-primitives v3 is out. Rebuilt the spring physics engine from scratch — it's now 60% smaller and doesn't drop frames on low-power devices. This was six weeks of very small, very satisfying performance wins.",
    tags: ["react", "animation", "opensource"],
    project: "motion-primitives",
    likes: 892,
    comments: 64,
    reposts: 145,
  },
  {
    id: "p3",
    author: "sofiavargas",
    type: "text",
    createdAt: "2026-07-22T19:40:00Z",
    content:
      "Quantized a 7B model down to 4-bit and it still runs coherent conversations on a Raspberry Pi 5. Not fast, but it runs. There's something delightful about watching a language model think on a $80 board.",
    tags: ["machinelearning", "edge-ai"],
    likes: 1230,
    comments: 87,
    reposts: 203,
  },
  {
    id: "p4",
    author: "graceokafor",
    type: "text",
    createdAt: "2026-07-22T13:15:00Z",
    content:
      "PSA: if your API keys are in a public repo's commit history, deleting the file doesn't help. Rotate the key. I say this every quarter because every quarter someone learns it the hard way.",
    tags: ["security", "appsec"],
    likes: 3410,
    comments: 156,
    reposts: 890,
  },
  {
    id: "p5",
    author: "priyaramesh",
    type: "poll",
    createdAt: "2026-07-22T09:00:00Z",
    content: "For a new B2B dashboard, what's your default charting library in 2026?",
    poll: {
      options: [
        { label: "Recharts", votes: 412 },
        { label: "visx", votes: 198 },
        { label: "Observable Plot", votes: 276 },
        { label: "D3 directly", votes: 89 },
      ],
      totalVotes: 975,
    },
    tags: ["frontend", "dataviz"],
    likes: 145,
    comments: 92,
    reposts: 8,
  },
  {
    id: "p6",
    author: "tomasnovak",
    type: "project-update",
    createdAt: "2026-07-21T21:30:00Z",
    content:
      "Devlog #14 for Hollow Hearth: added a full crafting system this week. Turns out balancing a crafting economy is basically doing spreadsheet math until 1am. The cozy roguelike genre is deceptively hard to get right.",
    tags: ["gamedev", "godot", "indiedev"],
    project: "hollow-hearth",
    likes: 340,
    comments: 41,
    reposts: 22,
  },
  {
    id: "p7",
    author: "davidkoenig",
    type: "text",
    createdAt: "2026-07-21T16:10:00Z",
    content:
      "Wrote a small Terraform drift detector that posts to Slack when someone changes infra outside of CI. Deployed it three weeks ago. It has already caught two 'quick fixes' made directly in the AWS console at 2am.",
    tags: ["devops", "terraform", "aws"],
    likes: 567,
    comments: 33,
    reposts: 78,
  },
  {
    id: "p8",
    author: "hannahfrost",
    type: "text",
    createdAt: "2026-07-21T08:45:00Z",
    content:
      "New guide is live: deploying edge functions with cold-start under 50ms. Includes the three mistakes I made that added 400ms I didn't notice for two weeks because my local network was fast enough to hide it.",
    tags: ["vercel", "edge", "webdev"],
    likes: 780,
    comments: 52,
    reposts: 190,
  },
  {
    id: "p9",
    author: "liuwei_dev",
    type: "text",
    createdAt: "2026-07-20T22:00:00Z",
    content:
      "Client wanted 'just a simple booking page' and four scope calls later we have multi-timezone support, recurring events, and a waitlist system. Simple is the most expensive word in a discovery call.",
    tags: ["freelance", "webdev"],
    likes: 2140,
    comments: 210,
    reposts: 340,
  },
  {
    id: "p10",
    author: "ritaesposito",
    type: "text",
    createdAt: "2026-07-20T15:25:00Z",
    content:
      "SwiftData's migration story finally clicked for me after rebuilding it three times. Writing up a full walkthrough this weekend because the official docs skip the part where your app actually has users.",
    tags: ["ios", "swift", "swiftdata"],
    likes: 445,
    comments: 29,
    reposts: 51,
  },
  {
    id: "p11",
    author: "marcusleblanc",
    type: "text",
    createdAt: "2026-07-19T18:00:00Z",
    content:
      "One year into managing instead of coding. The hardest skill wasn't delegation — it was resisting the urge to jump into a PR and 'just fix it myself' when I can see the fix immediately. Still working on it.",
    tags: ["engineering-management", "leadership"],
    likes: 1890,
    comments: 240,
    reposts: 120,
  },
  {
    id: "p12",
    author: "sofiavargas",
    type: "project-update",
    createdAt: "2026-07-19T11:30:00Z",
    content:
      "tinyinfer now supports speculative decoding. Roughly 1.8x throughput on the models I've tested. Benchmarks and a writeup on how the draft model selection works are in the repo.",
    tags: ["machinelearning", "opensource"],
    project: "tinyinfer",
    likes: 967,
    comments: 71,
    reposts: 188,
  },
  {
    id: "p13",
    author: "kenji_oda",
    type: "text",
    createdAt: "2026-07-18T13:50:00Z",
    content:
      "Unpopular opinion: most apps don't need a design system, they need three components used consistently. We spent two sprints building a system nobody outside our team ever used.",
    tags: ["frontend", "design-systems"],
    likes: 1560,
    comments: 302,
    reposts: 95,
  },
  {
    id: "p14",
    author: "amarapatel",
    type: "text",
    createdAt: "2026-07-18T09:10:00Z",
    content:
      "Reminder that 'eventually consistent' is a promise, not a plan. Write the reconciliation job first, then build the fast path. Skipping this step is how you get a 3am page about duplicate charges.",
    tags: ["backend", "distributed-systems"],
    likes: 1120,
    comments: 64,
    reposts: 210,
  },
  {
    id: "p15",
    author: "graceokafor",
    type: "project-update",
    createdAt: "2026-07-17T20:15:00Z",
    content:
      "Shipped header-audit v2 — a CLI that scans your deployed sites for missing security headers and generates a fix PR automatically. Free and open source, built it after auditing the same five headers manually too many times.",
    tags: ["security", "cli", "opensource"],
    project: "header-audit",
    likes: 2030,
    comments: 118,
    reposts: 410,
  },
  {
    id: "p16",
    author: "priyaramesh",
    type: "text",
    createdAt: "2026-07-17T12:00:00Z",
    content:
      "Founding engineer life: I've now written the onboarding flow, the billing system, and the internal admin tool nobody outside the company will ever see but that saves me two hours a day. Ship the boring thing.",
    tags: ["startups", "fintech"],
    likes: 640,
    comments: 45,
    reposts: 33,
  },
];

export const getPostsByAuthor = (username) => posts.filter((p) => p.author === username);
