// Realistic developer profiles used across feed, dashboard, profile pages,
// messaging, and the collaboration hub.

export const profiles = [
  {
    username: "amarapatel",
    name: "Amara Patel",
    role: "Senior Backend Engineer",
    company: "Rippling",
    location: "Austin, TX",
    bio: "Building payments infrastructure at scale. Previously at Stripe. I write about distributed systems and occasionally about my terrible garden.",
    stack: ["Go", "PostgreSQL", "Kafka", "Kubernetes"],
    followers: 2840,
    following: 312,
    joined: "2021-03-14",
    github: "amarapatel",
    website: "amarapatel.dev",
    openToWork: false,
    openToCollab: true,
    pinnedRepo: "ledger-core",
  },
  {
    username: "kenji_oda",
    name: "Kenji Oda",
    role: "Staff Frontend Engineer",
    company: "Linear",
    location: "Tokyo, JP",
    bio: "Obsessed with fast, feel-good interfaces. I maintain a few open-source animation libraries in my spare time.",
    stack: ["TypeScript", "React", "WebGL", "Rust"],
    followers: 5210,
    following: 180,
    joined: "2019-11-02",
    github: "kenjioda",
    website: "kenji.dev",
    openToWork: false,
    openToCollab: true,
    pinnedRepo: "motion-primitives",
  },
  {
    username: "sofiavargas",
    name: "Sofia Vargas",
    role: "ML Engineer",
    company: "Independent / Freelance",
    location: "Mexico City, MX",
    bio: "Fine-tuning small models so they run on things that aren't a data center. Writing a book on efficient inference.",
    stack: ["Python", "PyTorch", "CUDA", "ONNX"],
    followers: 3760,
    following: 402,
    joined: "2020-06-21",
    github: "sofiavargas",
    website: "sofiavargas.ai",
    openToWork: true,
    openToCollab: true,
    pinnedRepo: "tinyinfer",
  },
  {
    username: "davidkoenig",
    name: "David Koenig",
    role: "DevOps / Platform Engineer",
    company: "Deutsche Bahn Digital",
    location: "Berlin, DE",
    bio: "Keeping trains and their software running on time. Terraform enthusiast, on-call survivor.",
    stack: ["Terraform", "AWS", "Go", "Python"],
    followers: 1420,
    following: 265,
    joined: "2022-01-09",
    github: "dkoenig",
    website: "",
    openToWork: false,
    openToCollab: true,
    pinnedRepo: "drift-detector",
  },
  {
    username: "priyaramesh",
    name: "Priya Ramesh",
    role: "Founding Engineer",
    company: "Cascade (YC S24)",
    location: "San Francisco, CA",
    bio: "Building the boring parts of fintech so founders don't have to. Ex-Plaid. Always hiring engineer #4.",
    stack: ["TypeScript", "Next.js", "PostgreSQL", "tRPC"],
    followers: 6890,
    following: 511,
    joined: "2023-02-17",
    github: "priyaramesh",
    website: "cascade.so",
    openToWork: false,
    openToCollab: true,
    pinnedRepo: "cascade-api",
  },
  {
    username: "tomasnovak",
    name: "Tomáš Novák",
    role: "Game Developer",
    company: "Indie",
    location: "Prague, CZ",
    bio: "Making a cozy roguelike in Godot. Sharing devlogs every Friday. Previously shipped 3 mobile games nobody played.",
    stack: ["GDScript", "Godot", "C#", "Blender"],
    followers: 980,
    following: 140,
    joined: "2022-08-30",
    github: "tomasnovak",
    website: "novakgames.itch.io",
    openToWork: false,
    openToCollab: true,
    pinnedRepo: "hollow-hearth",
  },
  {
    username: "graceokafor",
    name: "Grace Okafor",
    role: "Security Engineer",
    company: "Cloudflare",
    location: "Lagos, NG",
    bio: "Appsec by day, CTF player by night. I break things so you don't have to find out the hard way.",
    stack: ["Python", "Go", "Burp Suite", "Rust"],
    followers: 4130,
    following: 220,
    joined: "2021-09-05",
    github: "graceokafor",
    website: "grace.security",
    openToWork: false,
    openToCollab: true,
    pinnedRepo: "header-audit",
  },
  {
    username: "liuwei_dev",
    name: "Liu Wei",
    role: "Full-Stack Engineer",
    company: "Freelance",
    location: "Singapore",
    bio: "Available for contract work. I ship MVPs in weeks, not quarters. DMs open for interesting problems.",
    stack: ["Next.js", "Supabase", "Tailwind", "Node.js"],
    followers: 1750,
    following: 390,
    joined: "2023-05-12",
    github: "liuweidev",
    website: "liuwei.dev",
    openToWork: true,
    openToCollab: true,
    pinnedRepo: "starter-saas-kit",
  },
  {
    username: "hannahfrost",
    name: "Hannah Frost",
    role: "Developer Advocate",
    company: "Vercel",
    location: "Toronto, CA",
    bio: "I write docs people actually read and record talks nobody skips through. Formerly taught CS at a bootcamp.",
    stack: ["JavaScript", "React", "Astro", "MDX"],
    followers: 8920,
    following: 615,
    joined: "2020-02-27",
    github: "hannahfrost",
    website: "hannahfrost.dev",
    openToWork: false,
    openToCollab: true,
    pinnedRepo: "edge-functions-cookbook",
  },
  {
    username: "marcusleblanc",
    name: "Marcus LeBlanc",
    role: "Engineering Manager",
    company: "Shopify",
    location: "Montreal, CA",
    bio: "Managing a team of 8 on checkout infra. Recovering IC. I write about the transition from coding to leading.",
    stack: ["Ruby", "Rails", "MySQL", "React"],
    followers: 3320,
    following: 298,
    joined: "2019-04-18",
    github: "mleblanc",
    website: "",
    openToWork: false,
    openToCollab: false,
    pinnedRepo: "checkout-extensions-sdk",
  },
  {
    username: "ritaesposito",
    name: "Rita Esposito",
    role: "iOS Engineer",
    company: "Duolingo",
    location: "Milan, IT",
    bio: "Swift and SwiftUI most days. Building the streak feature that ruins your sleep schedule. Sorry about that.",
    stack: ["Swift", "SwiftUI", "Combine", "XCTest"],
    followers: 2190,
    following: 175,
    joined: "2021-12-11",
    github: "ritaesposito",
    website: "rita.dev",
    openToWork: false,
    openToCollab: true,
    pinnedRepo: "swiftui-charts-kit",
  },
  {
    username: "you",
    name: "Jordan Ellis",
    role: "Full-Stack Engineer",
    company: "Open to opportunities",
    location: "Remote",
    bio: "Building side projects and looking for interesting collaborations. This is your DevLink profile — edit it any time in Settings.",
    stack: ["React", "Node.js", "PostgreSQL", "TypeScript"],
    followers: 128,
    following: 84,
    joined: "2024-11-01",
    github: "jordanellis",
    website: "",
    openToWork: true,
    openToCollab: true,
    pinnedRepo: "personal-site",
  },
];

export const getProfileByUsername = (username) =>
  profiles.find((p) => p.username === username);

export const currentUser = getProfileByUsername("you");
